### PR TITLE
feat(i18n): add fr-FR and es-MX translation files

### PR DESCRIPTION
**Pull request by infiniwave**

### CODE REVIEW

**Comment by infiniwave** [comment]
It doesn't matter to me. You should do what works best for you. On the same note, what about fr-FR?

**Comment by Jack-the-Pro101** [comment]
I have included the locale to be France French (fr-FR) because from my research it's the most universally understood version if you are not using slang.

**Comment by Jack-the-Pro101** [comment]
I think the best approach right now is to support the most universal dialects of languages so that we can fallback to them if we do not have a user's specific dialect. Then, in the future we can maybe support those more specific dialects.

That's why I'm not sure about the decision for Spanish because of how many dialects it has.

**Comment by Jack-the-Pro101** [comment]
I did some more research, it seems formal Spanish is also similar to French in that most of the dialects can understand each other without slang. In that case, can you rename the JSON file to just es.json without the specific localization suffix? I think we'll stick with that to designate that it's not locale specific.

**Comment by infiniwave** [comment]
Sounds good!

**Pull request merged**
